spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
server:
  port: 8080